#!/usr/bin/env bash
# =============================================================================
# detect_cameras.sh — find the real capture nodes and print a cameras: list.
#
# WHY THIS IS NOT A ONE-LINER. The obvious guess — "4 cameras, so /dev/video0
# through /dev/video3" — is WRONG on this rig, and wrong in a way that does not
# announce itself. Every UVC camera on a modern kernel creates TWO /dev/video*
# nodes: a video-capture node and a metadata node. On the paper's rig, 4x C920:
#
#     /dev/video0  CAPTURE   \_ camera 1
#     /dev/video1  METADATA  /
#     /dev/video2  CAPTURE   \_ camera 2
#     /dev/video3  METADATA  /
#     /dev/video4  CAPTURE   \_ camera 3
#     /dev/video5  METADATA  /
#     /dev/video6  CAPTURE   \_ camera 4
#     /dev/video7  METADATA  /
#
# so the capture nodes are 0,2,4,6. Opening /dev/video1 as a camera does not
# give you a helpful error; it gives you a stream of nothing.
#
# HOW THIS DECIDES — and why not by parity. "Even nodes are cameras" happens to
# be true here but is an artifact of this enumeration order: unplug one camera,
# add any other V4L2 device, or boot with a different probe order and it breaks
# silently. This script instead asks each node what it IS, via the V4L2
# VIDIOC_QUERYCAP ioctl, and keeps the ones reporting V4L2_CAP_VIDEO_CAPTURE
# (0x00000001) rather than V4L2_CAP_META_CAPTURE (0x00800000). That is the
# kernel's own answer.
#
# ORDERING. Cameras are ordered by USB bus_info (the physical port path), not by
# node number, so cam0..cam3 stay bound to the same physical camera across
# reboots and replugs. Node numbers do not survive a replug; bus paths do. This
# matters: camera_id is baked into every detection record and every per-camera
# statistic in the paper.
#
# Usage:
#     scripts/detect_cameras.sh              # human-readable table
#     scripts/detect_cameras.sh --yaml       # paste-able camera_params.yaml block
#     scripts/detect_cameras.sh --check      # exit 1 unless exactly --expect cams
#     scripts/detect_cameras.sh --expect 4 --check
# =============================================================================
set -euo pipefail

MODE="table"
EXPECT="${VISTA_EXPECT_CAMERAS:-4}"
CHECK=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --yaml)   MODE="yaml"; shift ;;
    --table)  MODE="table"; shift ;;
    --check)  CHECK=1; shift ;;
    --expect) EXPECT="$2"; shift 2 ;;
    -h|--help) sed -n '2,45p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

command -v python3 >/dev/null || { echo "python3 required" >&2; exit 2; }

# The probe is Python because VIDIOC_QUERYCAP is an ioctl and shell cannot issue
# one. v4l2-ctl would do it too, but it is not installed on a stock JetPack
# image and we refuse to make the camera list depend on an optional package.
python3 - "$MODE" "$EXPECT" "$CHECK" <<'PY'
import ctypes
import fcntl
import glob
import os
import sys

mode, expect, check = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])

# struct v4l2_capability from linux/videodev2.h — 104 bytes.
VIDIOC_QUERYCAP = 0x80685600          # _IOR('V', 0, struct v4l2_capability)
CAP_VIDEO_CAPTURE = 0x00000001
CAP_META_CAPTURE = 0x00800000


class Cap(ctypes.Structure):
    _fields_ = [
        ("driver", ctypes.c_char * 16),
        ("card", ctypes.c_char * 32),
        ("bus_info", ctypes.c_char * 32),
        ("version", ctypes.c_uint32),
        ("capabilities", ctypes.c_uint32),
        ("device_caps", ctypes.c_uint32),
        ("reserved", ctypes.c_uint32 * 3),
    ]


def query(path):
    cap = Cap()
    fd = None
    try:
        # O_NONBLOCK: opening a busy camera must not block this probe.
        fd = os.open(path, os.O_RDWR | os.O_NONBLOCK)
        fcntl.ioctl(fd, VIDIOC_QUERYCAP, cap)
    except OSError as e:
        return None, str(e)
    finally:
        if fd is not None:
            os.close(fd)
    return cap, None


nodes, errors = [], []
for path in sorted(glob.glob("/dev/video*"),
                   key=lambda p: int("".join(c for c in p if c.isdigit()) or 0)):
    cap, err = query(path)
    if cap is None:
        errors.append((path, err))
        continue
    dc = cap.device_caps
    if dc & CAP_VIDEO_CAPTURE:
        kind = "CAPTURE"
    elif dc & CAP_META_CAPTURE:
        kind = "metadata"
    else:
        kind = "other"
    nodes.append({
        "path": path,
        "kind": kind,
        "card": cap.card.decode(errors="replace").strip(),
        "bus": cap.bus_info.decode(errors="replace").strip(),
        "caps": dc,
    })

captures = [n for n in nodes if n["kind"] == "CAPTURE"]
# Stable physical ordering. bus_info looks like "usb-3610000.usb-4.2.1"; sorting
# it lexically groups by controller then by port path, which is what we want.
captures.sort(key=lambda n: n["bus"])

if mode == "yaml":
    print("# Generated by scripts/detect_cameras.sh — paste into "
          "config/camera_params.yaml.")
    print("# Order follows USB bus path, so camera_id survives replugs.")
    print("cameras:")
    for n in captures:
        print(f"  - device: {n['path']}    # {n['card']} @ {n['bus']}")
    if not captures:
        print("  # NONE FOUND")
else:
    if errors:
        print("Nodes that could not be probed:")
        for p, e in errors:
            print(f"  {p}: {e}")
        print("  (a 'Permission denied' here means your user is not in the "
              "'video' group)")
        print()
    print(f"{'node':<14}{'kind':<10}{'device_caps':<14}{'card':<26}bus")
    print("-" * 92)
    for n in nodes:
        print(f"{n['path']:<14}{n['kind']:<10}0x{n['caps']:08x}    "
              f"{n['card']:<26}{n['bus']}")
    print()
    print(f"{len(captures)} capture node(s), in stable bus order:")
    for i, n in enumerate(captures):
        print(f"  cam{i} -> {n['path']}   ({n['card']} @ {n['bus']})")
    meta = [n for n in nodes if n["kind"] == "metadata"]
    if meta:
        print(f"\n{len(meta)} metadata node(s) correctly excluded: "
              f"{', '.join(n['path'] for n in meta)}")
        print("These are NOT cameras. Listing one in camera_params.yaml yields "
              "a silent no-frame stream, not an error.")

if check:
    # stdout is block-buffered when piped; without this the stderr FAIL below
    # lands above the table it refers to.
    sys.stdout.flush()
    if len(captures) != expect:
        print(f"\nFAIL: expected {expect} capture node(s), found {len(captures)}.",
              file=sys.stderr)
        if len(captures) < expect:
            print("Fewer cameras than expected. Check: all cameras plugged in; "
                  "USB bandwidth (4x C920 @ 640x480 MJPG fits one USB-2 bus, "
                  "4x 720p does NOT — the 3rd camera fails STREAMON with "
                  "ENOSPC); and that your user is in the 'video' group.",
                  file=sys.stderr)
        sys.exit(1)
    print(f"\nOK: {len(captures)} capture node(s), as expected.")
PY
